### ISSUE TITLE
Looking for Senior Application Developer at the location of Baltimore, MD (Remote)

### ISSUE THREAD

**Issue by Samaragorati** [bmatusiak/bmatusiak.github.io#1]
Hi Professional,

This is Samar from RFRIT
Hope you are doing great!! 
RFRIT is looking for an Senior Application Developer. Please let me know if you are interested. Waiting for your response, thanks and have a great day!! 

Title: Senior Application Developer
Location: Baltimore, MD (Remote)
Visa: Any 

Mandatory skills:
 Development of Web Api using C# 
 .NET / .NET Core Experience Preferred 
 Fundamental understanding of dependency injection 
Fundamental understanding of Unit and Integration testing (NUnit, MSTest, etc.) 
Basic understanding of debugging via breakpoints 
Entity Framework 
Should have good knowledge of latest C# skills 
Git experience 
Extremely good in using LINQ & Lambda expressions 
 Understanding of IQueryables is preferred, but not necessary 
Understanding of when a loop is needed, over a LINQ select 
Should have worked on SQL Server Queries and stored procedure 
SQL Server Experience Preferred 
Experience with creating or altering database views 
Experience with creating or altering database stored procedures 

Not required, but nice to have: 
Experience with CI/CD (Builds & Deployments) 
Experience with Postman or Swagger 
Experience with asynchronous programming patterns 
Experience with data integrations 
Experience with resolving merge conflicts 
Experience with a defined branching structure.

Thanks & Regards,
Samara Gorati
Sr Technical Recruiter
Desk: 6093571513
Mobile: 8145813019
[Email: Samarasimha@rfrit.com](mailto:Email%3ANarsing.s@ssitsol.com)
6671 Deleon St, Irving,
TX-75039, USA
Website [www.rfrit.com](http://www.rfrit.com/)

**Comment by bmatusiak** [comment]
Taking a look at mandatory skills, this position doesn't fit me.

**Comment by Samaragorati** [comment]
Thanks for you response. will keep you posted. Have a nice day!

Regards,
Samar
