### ISSUE TITLE
Senior Node.js Developer- Remote

### ISSUE THREAD

**Issue by DeepakSondal** [bmatusiak/bmatusiak.github.io#2]
Hi Bradley, 
My name is Deepak and I work with Caspex.  I am currently looking for Senior Node.js Developer with one of our direct client. 
Please see the job details below and let me know if you would be interested in this role. 
If interested, please send me a copy of your resume, your contact details, your availability and a good time to connect with you.

Location- Remote
Job Title-  Senior Node.js Developer
Duration- 6-12+Months

Job Description:
Minimum Qualifications:
•	Experience programming in NodeJS.
•	Experience in Backend development, REST Services, microservice architecture, and related technologies
•	Experience with no-sql technologies like MongoDB or Azure Cosmos
•	Experience developing, configuring & deploying applications on Hapi.js/Express/Fastify.
•	Expertise in SaaS application development.
•	Experience with UNIX shell and scripting.
•	Comfortable writing tests in Jest
Preferred Qualifications:
•	Experience with Javascript, Typescript
•	Experience with Node streams

Regards,
Deepak Kumar 
Mobile: (510)455-3928 
Email: deepakk@caspex.com

**Comment by bmatusiak** [comment]
Hey.. I will contact you soon.

**Comment by DeepakSondal** [comment]
Hi Bradley- i am available Monday to Friday from 7am to 4pm PST. 
you can reach me at Deepakk@caspex.com/ Call- 510-455-3928/ Text- 408-868-3629
